// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        uuid.UUID          `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TableName string             `json:"table_name"`
	RecordID  uuid.UUID          `json:"record_id"`
	Action    string             `json:"action"`
	OldValues []byte             `json:"old_values"`
	NewValues []byte             `json:"new_values"`
	IpAddress *netip.Addr        `json:"ip_address"`
	UserAgent *string            `json:"user_agent"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID          uuid.UUID          `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	IsActive    *bool              `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Customer struct {
	ID            uuid.UUID          `json:"id"`
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	ContactPerson *string            `json:"contact_person"`
	Email         *string            `json:"email"`
	Phone         *string            `json:"phone"`
	Address       *string            `json:"address"`
	TaxID         *string            `json:"tax_id"`
	CreditLimit   pgtype.Numeric     `json:"credit_limit"`
	PaymentTerms  *int32             `json:"payment_terms"`
	IsActive      *bool              `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type CustomerInvoice struct {
	ID            uuid.UUID          `json:"id"`
	InvoiceNumber string             `json:"invoice_number"`
	CustomerID    uuid.UUID          `json:"customer_id"`
	SoID          pgtype.UUID        `json:"so_id"`
	InvoiceDate   pgtype.Date        `json:"invoice_date"`
	DueDate       pgtype.Date        `json:"due_date"`
	TotalAmount   pgtype.Numeric     `json:"total_amount"`
	PaidAmount    pgtype.Numeric     `json:"paid_amount"`
	Status        *string            `json:"status"`
	Notes         *string            `json:"notes"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type GoodsReceipt struct {
	ID            uuid.UUID          `json:"id"`
	ReceiptNumber string             `json:"receipt_number"`
	PoID          uuid.UUID          `json:"po_id"`
	ReceiptDate   pgtype.Date        `json:"receipt_date"`
	Notes         *string            `json:"notes"`
	ReceivedBy    pgtype.UUID        `json:"received_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type GoodsReceiptLine struct {
	ID         uuid.UUID          `json:"id"`
	ReceiptID  uuid.UUID          `json:"receipt_id"`
	PoLineID   uuid.UUID          `json:"po_line_id"`
	ProductID  uuid.UUID          `json:"product_id"`
	Quantity   pgtype.Numeric     `json:"quantity"`
	LineNumber int32              `json:"line_number"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Menu struct {
	ID        uuid.UUID          `json:"id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Path      *string            `json:"path"`
	Icon      *string            `json:"icon"`
	SortOrder *int32             `json:"sort_order"`
	IsActive  *bool              `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID            uuid.UUID          `json:"id"`
	PaymentNumber string             `json:"payment_number"`
	PaymentType   string             `json:"payment_type"`
	PartnerType   string             `json:"partner_type"`
	PartnerID     uuid.UUID          `json:"partner_id"`
	InvoiceID     pgtype.UUID        `json:"invoice_id"`
	PaymentDate   pgtype.Date        `json:"payment_date"`
	Amount        pgtype.Numeric     `json:"amount"`
	PaymentMethod *string            `json:"payment_method"`
	Reference     *string            `json:"reference"`
	Notes         *string            `json:"notes"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID          uuid.UUID          `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	UomID       uuid.UUID          `json:"uom_id"`
	ProductType *string            `json:"product_type"`
	CostPrice   pgtype.Numeric     `json:"cost_price"`
	SalePrice   pgtype.Numeric     `json:"sale_price"`
	MinStock    pgtype.Numeric     `json:"min_stock"`
	MaxStock    pgtype.Numeric     `json:"max_stock"`
	IsActive    *bool              `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type PurchaseOrder struct {
	ID           uuid.UUID          `json:"id"`
	PoNumber     string             `json:"po_number"`
	SupplierID   uuid.UUID          `json:"supplier_id"`
	OrderDate    pgtype.Date        `json:"order_date"`
	ExpectedDate pgtype.Date        `json:"expected_date"`
	Status       *string            `json:"status"`
	TotalAmount  pgtype.Numeric     `json:"total_amount"`
	Notes        *string            `json:"notes"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type PurchaseOrderLine struct {
	ID          uuid.UUID          `json:"id"`
	PoID        uuid.UUID          `json:"po_id"`
	ProductID   uuid.UUID          `json:"product_id"`
	Quantity    pgtype.Numeric     `json:"quantity"`
	UnitPrice   pgtype.Numeric     `json:"unit_price"`
	Subtotal    pgtype.Numeric     `json:"subtotal"`
	ReceivedQty pgtype.Numeric     `json:"received_qty"`
	LineNumber  int32              `json:"line_number"`
	Notes       *string            `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Quotation struct {
	ID          uuid.UUID          `json:"id"`
	QuoteNumber string             `json:"quote_number"`
	CustomerID  uuid.UUID          `json:"customer_id"`
	QuoteDate   pgtype.Date        `json:"quote_date"`
	ValidUntil  pgtype.Date        `json:"valid_until"`
	Status      *string            `json:"status"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Notes       *string            `json:"notes"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type QuotationLine struct {
	ID         uuid.UUID          `json:"id"`
	QuoteID    uuid.UUID          `json:"quote_id"`
	ProductID  uuid.UUID          `json:"product_id"`
	Quantity   pgtype.Numeric     `json:"quantity"`
	UnitPrice  pgtype.Numeric     `json:"unit_price"`
	Subtotal   pgtype.Numeric     `json:"subtotal"`
	LineNumber int32              `json:"line_number"`
	Notes      *string            `json:"notes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID          uuid.UUID          `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	IsActive    *bool              `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RoleMenu struct {
	ID        uuid.UUID          `json:"id"`
	RoleID    uuid.UUID          `json:"role_id"`
	MenuID    uuid.UUID          `json:"menu_id"`
	CanCreate *bool              `json:"can_create"`
	CanRead   *bool              `json:"can_read"`
	CanUpdate *bool              `json:"can_update"`
	CanDelete *bool              `json:"can_delete"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SalesOrder struct {
	ID           uuid.UUID          `json:"id"`
	SoNumber     string             `json:"so_number"`
	CustomerID   uuid.UUID          `json:"customer_id"`
	QuoteID      pgtype.UUID        `json:"quote_id"`
	OrderDate    pgtype.Date        `json:"order_date"`
	DeliveryDate pgtype.Date        `json:"delivery_date"`
	Status       *string            `json:"status"`
	TotalAmount  pgtype.Numeric     `json:"total_amount"`
	Notes        *string            `json:"notes"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type SalesOrderLine struct {
	ID           uuid.UUID          `json:"id"`
	SoID         uuid.UUID          `json:"so_id"`
	ProductID    uuid.UUID          `json:"product_id"`
	Quantity     pgtype.Numeric     `json:"quantity"`
	UnitPrice    pgtype.Numeric     `json:"unit_price"`
	Subtotal     pgtype.Numeric     `json:"subtotal"`
	DeliveredQty pgtype.Numeric     `json:"delivered_qty"`
	LineNumber   int32              `json:"line_number"`
	Notes        *string            `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type StockAdjustment struct {
	ID               uuid.UUID          `json:"id"`
	AdjustmentNumber string             `json:"adjustment_number"`
	LocationID       uuid.UUID          `json:"location_id"`
	AdjustmentDate   pgtype.Date        `json:"adjustment_date"`
	Reason           *string            `json:"reason"`
	Status           *string            `json:"status"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type StockAdjustmentLine struct {
	ID             uuid.UUID          `json:"id"`
	AdjustmentID   uuid.UUID          `json:"adjustment_id"`
	ProductID      uuid.UUID          `json:"product_id"`
	QuantityBefore pgtype.Numeric     `json:"quantity_before"`
	QuantityAfter  pgtype.Numeric     `json:"quantity_after"`
	Difference     pgtype.Numeric     `json:"difference"`
	LineNumber     int32              `json:"line_number"`
	Notes          *string            `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type StockBalance struct {
	ID           uuid.UUID          `json:"id"`
	ProductID    uuid.UUID          `json:"product_id"`
	LocationID   uuid.UUID          `json:"location_id"`
	Quantity     pgtype.Numeric     `json:"quantity"`
	ReservedQty  pgtype.Numeric     `json:"reserved_qty"`
	AvailableQty pgtype.Numeric     `json:"available_qty"`
	LastUpdated  pgtype.Timestamptz `json:"last_updated"`
}

type StockLocation struct {
	ID           uuid.UUID          `json:"id"`
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	LocationType *string            `json:"location_type"`
	IsActive     *bool              `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type StockMovement struct {
	ID             uuid.UUID          `json:"id"`
	MovementNumber string             `json:"movement_number"`
	ProductID      uuid.UUID          `json:"product_id"`
	LocationID     uuid.UUID          `json:"location_id"`
	MovementType   string             `json:"movement_type"`
	Quantity       pgtype.Numeric     `json:"quantity"`
	ReferenceType  *string            `json:"reference_type"`
	ReferenceID    pgtype.UUID        `json:"reference_id"`
	MovementDate   pgtype.Timestamptz `json:"movement_date"`
	Notes          *string            `json:"notes"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Supplier struct {
	ID            uuid.UUID          `json:"id"`
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	ContactPerson *string            `json:"contact_person"`
	Email         *string            `json:"email"`
	Phone         *string            `json:"phone"`
	Address       *string            `json:"address"`
	TaxID         *string            `json:"tax_id"`
	PaymentTerms  *int32             `json:"payment_terms"`
	IsActive      *bool              `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type SupplierBill struct {
	ID          uuid.UUID          `json:"id"`
	BillNumber  string             `json:"bill_number"`
	SupplierID  uuid.UUID          `json:"supplier_id"`
	PoID        pgtype.UUID        `json:"po_id"`
	BillDate    pgtype.Date        `json:"bill_date"`
	DueDate     pgtype.Date        `json:"due_date"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	PaidAmount  pgtype.Numeric     `json:"paid_amount"`
	Status      *string            `json:"status"`
	Notes       *string            `json:"notes"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UnitsOfMeasure struct {
	ID               uuid.UUID          `json:"id"`
	Code             string             `json:"code"`
	Name             string             `json:"name"`
	UnitType         string             `json:"unit_type"`
	IsBaseUnit       *bool              `json:"is_base_unit"`
	ConversionFactor pgtype.Numeric     `json:"conversion_factor"`
	IsActive         *bool              `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	IsActive     *bool              `json:"is_active"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type UserRole struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	RoleID     uuid.UUID          `json:"role_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
	AssignedBy pgtype.UUID        `json:"assigned_by"`
}
