// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) (AssignRoleToUserRow, error)
	CheckEmailExists(ctx context.Context, email string) (bool, error)
	CheckUsernameExists(ctx context.Context, username string) (bool, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (CreateCategoryRow, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (CreateCustomerRow, error)
	CreateCustomerInvoice(ctx context.Context, arg CreateCustomerInvoiceParams) (CreateCustomerInvoiceRow, error)
	CreateGoodsReceipt(ctx context.Context, arg CreateGoodsReceiptParams) (CreateGoodsReceiptRow, error)
	CreateGoodsReceiptLine(ctx context.Context, arg CreateGoodsReceiptLineParams) (CreateGoodsReceiptLineRow, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error)
	CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (CreatePurchaseOrderRow, error)
	CreatePurchaseOrderLine(ctx context.Context, arg CreatePurchaseOrderLineParams) (CreatePurchaseOrderLineRow, error)
	CreateQuotation(ctx context.Context, arg CreateQuotationParams) (CreateQuotationRow, error)
	CreateQuotationLine(ctx context.Context, arg CreateQuotationLineParams) (CreateQuotationLineRow, error)
	CreateSalesOrder(ctx context.Context, arg CreateSalesOrderParams) (CreateSalesOrderRow, error)
	CreateSalesOrderLine(ctx context.Context, arg CreateSalesOrderLineParams) (CreateSalesOrderLineRow, error)
	CreateStockAdjustment(ctx context.Context, arg CreateStockAdjustmentParams) (CreateStockAdjustmentRow, error)
	CreateStockAdjustmentLine(ctx context.Context, arg CreateStockAdjustmentLineParams) (CreateStockAdjustmentLineRow, error)
	CreateStockLocation(ctx context.Context, arg CreateStockLocationParams) (CreateStockLocationRow, error)
	CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) (CreateStockMovementRow, error)
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (CreateSupplierRow, error)
	CreateSupplierBill(ctx context.Context, arg CreateSupplierBillParams) (CreateSupplierBillRow, error)
	CreateUnitOfMeasure(ctx context.Context, arg CreateUnitOfMeasureParams) (CreateUnitOfMeasureRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetAccountsPayableSummary(ctx context.Context, dollar_1 uuid.UUID) ([]GetAccountsPayableSummaryRow, error)
	GetAccountsReceivableSummary(ctx context.Context, dollar_1 uuid.UUID) ([]GetAccountsReceivableSummaryRow, error)
	GetAgingReceivables(ctx context.Context) ([]GetAgingReceivablesRow, error)
	GetCashFlowSummary(ctx context.Context, arg GetCashFlowSummaryParams) (GetCashFlowSummaryRow, error)
	GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error)
	GetCustomerByID(ctx context.Context, id uuid.UUID) (GetCustomerByIDRow, error)
	GetCustomerInvoiceByID(ctx context.Context, id uuid.UUID) (GetCustomerInvoiceByIDRow, error)
	GetGoodsReceiptsByPO(ctx context.Context, poID uuid.UUID) ([]GetGoodsReceiptsByPORow, error)
	GetGrossProfitByProduct(ctx context.Context, arg GetGrossProfitByProductParams) ([]GetGrossProfitByProductRow, error)
	GetGrossProfitSummary(ctx context.Context, arg GetGrossProfitSummaryParams) (GetGrossProfitSummaryRow, error)
	GetPaymentByID(ctx context.Context, id uuid.UUID) (GetPaymentByIDRow, error)
	GetProductByCode(ctx context.Context, code string) (GetProductByCodeRow, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error)
	GetPurchaseOrderByID(ctx context.Context, id uuid.UUID) (GetPurchaseOrderByIDRow, error)
	GetPurchaseOrderLines(ctx context.Context, poID uuid.UUID) ([]GetPurchaseOrderLinesRow, error)
	GetQuotationByID(ctx context.Context, id uuid.UUID) (GetQuotationByIDRow, error)
	GetQuotationLines(ctx context.Context, quoteID uuid.UUID) ([]GetQuotationLinesRow, error)
	GetSalesOrderByID(ctx context.Context, id uuid.UUID) (GetSalesOrderByIDRow, error)
	GetSalesOrderLines(ctx context.Context, soID uuid.UUID) ([]GetSalesOrderLinesRow, error)
	GetStockAdjustmentByID(ctx context.Context, id uuid.UUID) (GetStockAdjustmentByIDRow, error)
	GetStockAdjustmentLines(ctx context.Context, adjustmentID uuid.UUID) ([]GetStockAdjustmentLinesRow, error)
	GetStockBalance(ctx context.Context, arg GetStockBalanceParams) (GetStockBalanceRow, error)
	GetSupplierBillByID(ctx context.Context, id uuid.UUID) (GetSupplierBillByIDRow, error)
	GetSupplierByID(ctx context.Context, id uuid.UUID) (GetSupplierByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	GetUserMenus(ctx context.Context, userID uuid.UUID) ([]GetUserMenusRow, error)
	GetUserRoles(ctx context.Context, userID uuid.UUID) ([]GetUserRolesRow, error)
	ListActiveCategories(ctx context.Context) ([]ListActiveCategoriesRow, error)
	ListActiveCustomers(ctx context.Context) ([]ListActiveCustomersRow, error)
	ListActiveProducts(ctx context.Context, dollar_1 uuid.UUID) ([]ListActiveProductsRow, error)
	ListActiveStockLocations(ctx context.Context) ([]ListActiveStockLocationsRow, error)
	ListActiveSuppliers(ctx context.Context) ([]ListActiveSuppliersRow, error)
	ListActiveUoM(ctx context.Context) ([]ListActiveUoMRow, error)
	ListCustomerInvoices(ctx context.Context, arg ListCustomerInvoicesParams) ([]ListCustomerInvoicesRow, error)
	ListPayments(ctx context.Context, arg ListPaymentsParams) ([]ListPaymentsRow, error)
	ListPurchaseOrders(ctx context.Context, arg ListPurchaseOrdersParams) ([]ListPurchaseOrdersRow, error)
	ListQuotations(ctx context.Context, arg ListQuotationsParams) ([]ListQuotationsRow, error)
	ListSalesOrders(ctx context.Context, arg ListSalesOrdersParams) ([]ListSalesOrdersRow, error)
	ListStockAdjustments(ctx context.Context, arg ListStockAdjustmentsParams) ([]ListStockAdjustmentsRow, error)
	ListStockBalances(ctx context.Context, arg ListStockBalancesParams) ([]ListStockBalancesRow, error)
	ListStockMovements(ctx context.Context, arg ListStockMovementsParams) ([]ListStockMovementsRow, error)
	ListSupplierBills(ctx context.Context, arg ListSupplierBillsParams) ([]ListSupplierBillsRow, error)
	RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error
	UpdateCustomerInvoicePaidAmount(ctx context.Context, arg UpdateCustomerInvoicePaidAmountParams) error
	UpdatePOLineReceivedQty(ctx context.Context, arg UpdatePOLineReceivedQtyParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdatePurchaseOrderStatus(ctx context.Context, arg UpdatePurchaseOrderStatusParams) error
	UpdateQuotationStatus(ctx context.Context, arg UpdateQuotationStatusParams) error
	UpdateSOLineDeliveredQty(ctx context.Context, arg UpdateSOLineDeliveredQtyParams) error
	UpdateSalesOrderStatus(ctx context.Context, arg UpdateSalesOrderStatusParams) error
	UpdateStockAdjustmentStatus(ctx context.Context, arg UpdateStockAdjustmentStatusParams) error
	UpdateStockQuantity(ctx context.Context, arg UpdateStockQuantityParams) error
	UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) error
	UpdateSupplierBillPaidAmount(ctx context.Context, arg UpdateSupplierBillPaidAmountParams) error
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpsertStockBalance(ctx context.Context, arg UpsertStockBalanceParams) (UpsertStockBalanceRow, error)
}

var _ Querier = (*Queries)(nil)
