// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package dbgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const assignRoleToUser = `-- name: AssignRoleToUser :one
INSERT INTO user_roles (
    user_id,
    role_id,
    assigned_by
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, role_id, assigned_at
`

type AssignRoleToUserParams struct {
	UserID     uuid.UUID     `json:"user_id"`
	RoleID     uuid.UUID     `json:"role_id"`
	AssignedBy uuid.NullUUID `json:"assigned_by"`
}

type AssignRoleToUserRow struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	RoleID     uuid.UUID    `json:"role_id"`
	AssignedAt sql.NullTime `json:"assigned_at"`
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) (AssignRoleToUserRow, error) {
	row := q.queryRow(ctx, q.assignRoleToUserStmt, assignRoleToUser, arg.UserID, arg.RoleID, arg.AssignedBy)
	var i AssignRoleToUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.AssignedAt,
	)
	return i, err
}

const checkUserMenuAccess = `-- name: CheckUserMenuAccess :one
SELECT 
    COALESCE(MAX(rm.can_read::int), 0) > 0 as can_read,
    COALESCE(MAX(rm.can_create::int), 0) > 0 as can_create,
    COALESCE(MAX(rm.can_update::int), 0) > 0 as can_update,
    COALESCE(MAX(rm.can_delete::int), 0) > 0 as can_delete
FROM role_menus rm
INNER JOIN user_roles ur ON rm.role_id = ur.role_id
INNER JOIN menus m ON rm.menu_id = m.id
WHERE ur.user_id = $1 
    AND m.code = $2
    AND m.is_active = true
`

type CheckUserMenuAccessParams struct {
	UserID uuid.UUID `json:"user_id"`
	Code   string    `json:"code"`
}

type CheckUserMenuAccessRow struct {
	CanRead   bool `json:"can_read"`
	CanCreate bool `json:"can_create"`
	CanUpdate bool `json:"can_update"`
	CanDelete bool `json:"can_delete"`
}

func (q *Queries) CheckUserMenuAccess(ctx context.Context, arg CheckUserMenuAccessParams) (CheckUserMenuAccessRow, error) {
	row := q.queryRow(ctx, q.checkUserMenuAccessStmt, checkUserMenuAccess, arg.UserID, arg.Code)
	var i CheckUserMenuAccessRow
	err := row.Scan(
		&i.CanRead,
		&i.CanCreate,
		&i.CanUpdate,
		&i.CanDelete,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    email,
    password_hash,
    full_name,
    is_active
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, username, email, full_name, is_active, created_at
`

type CreateUserParams struct {
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	FullName     string       `json:"full_name"`
	IsActive     sql.NullBool `json:"is_active"`
}

type CreateUserRow struct {
	ID        uuid.UUID    `json:"id"`
	Username  string       `json:"username"`
	Email     string       `json:"email"`
	FullName  string       `json:"full_name"`
	IsActive  sql.NullBool `json:"is_active"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.IsActive,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getMenusByUserID = `-- name: GetMenusByUserID :many
SELECT DISTINCT
    m.id,
    m.parent_id,
    m.code,
    m.name,
    m.path,
    m.icon,
    m.sort_order,
    rm.can_create,
    rm.can_read,
    rm.can_update,
    rm.can_delete
FROM menus m
INNER JOIN role_menus rm ON m.id = rm.menu_id
INNER JOIN user_roles ur ON rm.role_id = ur.role_id
WHERE ur.user_id = $1 
    AND m.is_active = true
ORDER BY m.sort_order, m.name
`

type GetMenusByUserIDRow struct {
	ID        uuid.UUID      `json:"id"`
	ParentID  uuid.NullUUID  `json:"parent_id"`
	Code      string         `json:"code"`
	Name      string         `json:"name"`
	Path      sql.NullString `json:"path"`
	Icon      sql.NullString `json:"icon"`
	SortOrder sql.NullInt32  `json:"sort_order"`
	CanCreate sql.NullBool   `json:"can_create"`
	CanRead   sql.NullBool   `json:"can_read"`
	CanUpdate sql.NullBool   `json:"can_update"`
	CanDelete sql.NullBool   `json:"can_delete"`
}

func (q *Queries) GetMenusByUserID(ctx context.Context, userID uuid.UUID) ([]GetMenusByUserIDRow, error) {
	rows, err := q.query(ctx, q.getMenusByUserIDStmt, getMenusByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMenusByUserIDRow
	for rows.Next() {
		var i GetMenusByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Code,
			&i.Name,
			&i.Path,
			&i.Icon,
			&i.SortOrder,
			&i.CanCreate,
			&i.CanRead,
			&i.CanUpdate,
			&i.CanDelete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleByCode = `-- name: GetRoleByCode :one
SELECT 
    id,
    code,
    name,
    description,
    is_active,
    created_at
FROM roles
WHERE code = $1
    AND is_active = true
LIMIT 1
`

type GetRoleByCodeRow struct {
	ID          uuid.UUID      `json:"id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

func (q *Queries) GetRoleByCode(ctx context.Context, code string) (GetRoleByCodeRow, error) {
	row := q.queryRow(ctx, q.getRoleByCodeStmt, getRoleByCode, code)
	var i GetRoleByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT 
    id,
    username,
    email,
    full_name,
    is_active,
    last_login_at,
    created_at,
    updated_at
FROM users
WHERE id = $1 
    AND deleted_at IS NULL
LIMIT 1
`

type GetUserByIDRow struct {
	ID          uuid.UUID    `json:"id"`
	Username    string       `json:"username"`
	Email       string       `json:"email"`
	FullName    string       `json:"full_name"`
	IsActive    sql.NullBool `json:"is_active"`
	LastLoginAt sql.NullTime `json:"last_login_at"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT 
    id,
    username,
    email,
    password_hash,
    full_name,
    is_active,
    last_login_at,
    created_at,
    updated_at
FROM users
WHERE username = $1 
    AND deleted_at IS NULL
LIMIT 1
`

type GetUserByUsernameRow struct {
	ID           uuid.UUID    `json:"id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	FullName     string       `json:"full_name"`
	IsActive     sql.NullBool `json:"is_active"`
	LastLoginAt  sql.NullTime `json:"last_login_at"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.queryRow(ctx, q.getUserByUsernameStmt, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT 
    r.id,
    r.code,
    r.name,
    r.description,
    ur.assigned_at
FROM roles r
INNER JOIN user_roles ur ON r.id = ur.role_id
WHERE ur.user_id = $1 
    AND r.is_active = true
ORDER BY r.name
`

type GetUserRolesRow struct {
	ID          uuid.UUID      `json:"id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	AssignedAt  sql.NullTime   `json:"assigned_at"`
}

func (q *Queries) GetUserRoles(ctx context.Context, userID uuid.UUID) ([]GetUserRolesRow, error) {
	rows, err := q.query(ctx, q.getUserRolesStmt, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRolesRow
	for rows.Next() {
		var i GetUserRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveUsers = `-- name: ListActiveUsers :many
SELECT 
    id,
    username,
    email,
    full_name,
    is_active,
    last_login_at,
    created_at
FROM users
WHERE deleted_at IS NULL
    AND ($1::boolean IS NULL OR is_active = $1)
ORDER BY full_name
`

type ListActiveUsersRow struct {
	ID          uuid.UUID    `json:"id"`
	Username    string       `json:"username"`
	Email       string       `json:"email"`
	FullName    string       `json:"full_name"`
	IsActive    sql.NullBool `json:"is_active"`
	LastLoginAt sql.NullTime `json:"last_login_at"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

func (q *Queries) ListActiveUsers(ctx context.Context, dollar_1 bool) ([]ListActiveUsersRow, error) {
	rows, err := q.query(ctx, q.listActiveUsersStmt, listActiveUsers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveUsersRow
	for rows.Next() {
		var i ListActiveUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FullName,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.updateUserLastLoginStmt, updateUserLastLogin, id)
	return err
}
