// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package dbgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const assignRoleToUser = `-- name: AssignRoleToUser :one
INSERT INTO user_roles (
    user_id,
    role_id,
    assigned_by
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, role_id, assigned_at
`

type AssignRoleToUserParams struct {
	UserID     uuid.UUID     `json:"user_id"`
	RoleID     uuid.UUID     `json:"role_id"`
	AssignedBy uuid.NullUUID `json:"assigned_by"`
}

type AssignRoleToUserRow struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	RoleID     uuid.UUID    `json:"role_id"`
	AssignedAt sql.NullTime `json:"assigned_at"`
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) (AssignRoleToUserRow, error) {
	row := q.queryRow(ctx, q.assignRoleToUserStmt, assignRoleToUser, arg.UserID, arg.RoleID, arg.AssignedBy)
	var i AssignRoleToUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.AssignedAt,
	)
	return i, err
}

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT EXISTS(
    SELECT 1 FROM users 
    WHERE email = $1 
    AND deleted_at IS NULL
) as exists
`

func (q *Queries) CheckEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.queryRow(ctx, q.checkEmailExistsStmt, checkEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUsernameExists = `-- name: CheckUsernameExists :one
SELECT EXISTS(
    SELECT 1 FROM users 
    WHERE username = $1 
    AND deleted_at IS NULL
) as exists
`

func (q *Queries) CheckUsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.queryRow(ctx, q.checkUsernameExistsStmt, checkUsernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    email,
    password_hash,
    full_name,
    is_active
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, username, email, full_name, is_active, created_at
`

type CreateUserParams struct {
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	FullName     string       `json:"full_name"`
	IsActive     sql.NullBool `json:"is_active"`
}

type CreateUserRow struct {
	ID        uuid.UUID    `json:"id"`
	Username  string       `json:"username"`
	Email     string       `json:"email"`
	FullName  string       `json:"full_name"`
	IsActive  sql.NullBool `json:"is_active"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.IsActive,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT 
    id,
    username,
    email,
    password_hash,
    full_name,
    is_active,
    last_login_at,
    created_at,
    updated_at
FROM users
WHERE email = $1 
    AND deleted_at IS NULL
LIMIT 1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID    `json:"id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	FullName     string       `json:"full_name"`
	IsActive     sql.NullBool `json:"is_active"`
	LastLoginAt  sql.NullTime `json:"last_login_at"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT 
    id,
    username,
    email,
    full_name,
    is_active,
    last_login_at,
    created_at,
    updated_at
FROM users
WHERE id = $1 
    AND deleted_at IS NULL
LIMIT 1
`

type GetUserByIDRow struct {
	ID          uuid.UUID    `json:"id"`
	Username    string       `json:"username"`
	Email       string       `json:"email"`
	FullName    string       `json:"full_name"`
	IsActive    sql.NullBool `json:"is_active"`
	LastLoginAt sql.NullTime `json:"last_login_at"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT 
    id,
    username,
    email,
    password_hash,
    full_name,
    is_active,
    last_login_at,
    created_at,
    updated_at
FROM users
WHERE username = $1 
    AND deleted_at IS NULL
LIMIT 1
`

type GetUserByUsernameRow struct {
	ID           uuid.UUID    `json:"id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	FullName     string       `json:"full_name"`
	IsActive     sql.NullBool `json:"is_active"`
	LastLoginAt  sql.NullTime `json:"last_login_at"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.queryRow(ctx, q.getUserByUsernameStmt, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserMenus = `-- name: GetUserMenus :many
SELECT DISTINCT
    m.id,
    m.parent_id,
    m.code,
    m.name,
    m.path,
    m.icon,
    m.sort_order,
    MAX(rm.can_create::int) as can_create,
    MAX(rm.can_read::int) as can_read,
    MAX(rm.can_update::int) as can_update,
    MAX(rm.can_delete::int) as can_delete
FROM menus m
INNER JOIN role_menus rm ON m.id = rm.menu_id
INNER JOIN user_roles ur ON rm.role_id = ur.role_id
WHERE ur.user_id = $1 
    AND m.is_active = true
GROUP BY m.id, m.parent_id, m.code, m.name, m.path, m.icon, m.sort_order
ORDER BY m.sort_order, m.name
`

type GetUserMenusRow struct {
	ID        uuid.UUID      `json:"id"`
	ParentID  uuid.NullUUID  `json:"parent_id"`
	Code      string         `json:"code"`
	Name      string         `json:"name"`
	Path      sql.NullString `json:"path"`
	Icon      sql.NullString `json:"icon"`
	SortOrder sql.NullInt32  `json:"sort_order"`
	CanCreate interface{}    `json:"can_create"`
	CanRead   interface{}    `json:"can_read"`
	CanUpdate interface{}    `json:"can_update"`
	CanDelete interface{}    `json:"can_delete"`
}

func (q *Queries) GetUserMenus(ctx context.Context, userID uuid.UUID) ([]GetUserMenusRow, error) {
	rows, err := q.query(ctx, q.getUserMenusStmt, getUserMenus, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserMenusRow
	for rows.Next() {
		var i GetUserMenusRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Code,
			&i.Name,
			&i.Path,
			&i.Icon,
			&i.SortOrder,
			&i.CanCreate,
			&i.CanRead,
			&i.CanUpdate,
			&i.CanDelete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT 
    r.id,
    r.code,
    r.name,
    r.description,
    ur.assigned_at
FROM roles r
INNER JOIN user_roles ur ON r.id = ur.role_id
WHERE ur.user_id = $1 
    AND r.is_active = true
ORDER BY r.name
`

type GetUserRolesRow struct {
	ID          uuid.UUID      `json:"id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	AssignedAt  sql.NullTime   `json:"assigned_at"`
}

func (q *Queries) GetUserRoles(ctx context.Context, userID uuid.UUID) ([]GetUserRolesRow, error) {
	rows, err := q.query(ctx, q.getUserRolesStmt, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRolesRow
	for rows.Next() {
		var i GetUserRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.updateUserLastLoginStmt, updateUserLastLogin, id)
	return err
}
