// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.assignRoleToUserStmt, err = db.PrepareContext(ctx, assignRoleToUser); err != nil {
		return nil, fmt.Errorf("error preparing query AssignRoleToUser: %w", err)
	}
	if q.checkUserMenuAccessStmt, err = db.PrepareContext(ctx, checkUserMenuAccess); err != nil {
		return nil, fmt.Errorf("error preparing query CheckUserMenuAccess: %w", err)
	}
	if q.createCategoryStmt, err = db.PrepareContext(ctx, createCategory); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCategory: %w", err)
	}
	if q.createCustomerStmt, err = db.PrepareContext(ctx, createCustomer); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCustomer: %w", err)
	}
	if q.createCustomerInvoiceStmt, err = db.PrepareContext(ctx, createCustomerInvoice); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCustomerInvoice: %w", err)
	}
	if q.createGoodsReceiptStmt, err = db.PrepareContext(ctx, createGoodsReceipt); err != nil {
		return nil, fmt.Errorf("error preparing query CreateGoodsReceipt: %w", err)
	}
	if q.createGoodsReceiptLineStmt, err = db.PrepareContext(ctx, createGoodsReceiptLine); err != nil {
		return nil, fmt.Errorf("error preparing query CreateGoodsReceiptLine: %w", err)
	}
	if q.createPaymentStmt, err = db.PrepareContext(ctx, createPayment); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePayment: %w", err)
	}
	if q.createProductStmt, err = db.PrepareContext(ctx, createProduct); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProduct: %w", err)
	}
	if q.createPurchaseOrderStmt, err = db.PrepareContext(ctx, createPurchaseOrder); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePurchaseOrder: %w", err)
	}
	if q.createPurchaseOrderLineStmt, err = db.PrepareContext(ctx, createPurchaseOrderLine); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePurchaseOrderLine: %w", err)
	}
	if q.createQuotationStmt, err = db.PrepareContext(ctx, createQuotation); err != nil {
		return nil, fmt.Errorf("error preparing query CreateQuotation: %w", err)
	}
	if q.createQuotationLineStmt, err = db.PrepareContext(ctx, createQuotationLine); err != nil {
		return nil, fmt.Errorf("error preparing query CreateQuotationLine: %w", err)
	}
	if q.createSalesOrderStmt, err = db.PrepareContext(ctx, createSalesOrder); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSalesOrder: %w", err)
	}
	if q.createSalesOrderLineStmt, err = db.PrepareContext(ctx, createSalesOrderLine); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSalesOrderLine: %w", err)
	}
	if q.createStockAdjustmentStmt, err = db.PrepareContext(ctx, createStockAdjustment); err != nil {
		return nil, fmt.Errorf("error preparing query CreateStockAdjustment: %w", err)
	}
	if q.createStockAdjustmentLineStmt, err = db.PrepareContext(ctx, createStockAdjustmentLine); err != nil {
		return nil, fmt.Errorf("error preparing query CreateStockAdjustmentLine: %w", err)
	}
	if q.createStockLocationStmt, err = db.PrepareContext(ctx, createStockLocation); err != nil {
		return nil, fmt.Errorf("error preparing query CreateStockLocation: %w", err)
	}
	if q.createStockMovementStmt, err = db.PrepareContext(ctx, createStockMovement); err != nil {
		return nil, fmt.Errorf("error preparing query CreateStockMovement: %w", err)
	}
	if q.createSupplierStmt, err = db.PrepareContext(ctx, createSupplier); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSupplier: %w", err)
	}
	if q.createSupplierBillStmt, err = db.PrepareContext(ctx, createSupplierBill); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSupplierBill: %w", err)
	}
	if q.createUnitOfMeasureStmt, err = db.PrepareContext(ctx, createUnitOfMeasure); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUnitOfMeasure: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.getAccountsPayableSummaryStmt, err = db.PrepareContext(ctx, getAccountsPayableSummary); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccountsPayableSummary: %w", err)
	}
	if q.getAccountsReceivableSummaryStmt, err = db.PrepareContext(ctx, getAccountsReceivableSummary); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccountsReceivableSummary: %w", err)
	}
	if q.getAgingReceivablesStmt, err = db.PrepareContext(ctx, getAgingReceivables); err != nil {
		return nil, fmt.Errorf("error preparing query GetAgingReceivables: %w", err)
	}
	if q.getCashFlowSummaryStmt, err = db.PrepareContext(ctx, getCashFlowSummary); err != nil {
		return nil, fmt.Errorf("error preparing query GetCashFlowSummary: %w", err)
	}
	if q.getCategoryByIDStmt, err = db.PrepareContext(ctx, getCategoryByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCategoryByID: %w", err)
	}
	if q.getCustomerByIDStmt, err = db.PrepareContext(ctx, getCustomerByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCustomerByID: %w", err)
	}
	if q.getCustomerInvoiceByIDStmt, err = db.PrepareContext(ctx, getCustomerInvoiceByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCustomerInvoiceByID: %w", err)
	}
	if q.getGoodsReceiptsByPOStmt, err = db.PrepareContext(ctx, getGoodsReceiptsByPO); err != nil {
		return nil, fmt.Errorf("error preparing query GetGoodsReceiptsByPO: %w", err)
	}
	if q.getGrossProfitByProductStmt, err = db.PrepareContext(ctx, getGrossProfitByProduct); err != nil {
		return nil, fmt.Errorf("error preparing query GetGrossProfitByProduct: %w", err)
	}
	if q.getGrossProfitSummaryStmt, err = db.PrepareContext(ctx, getGrossProfitSummary); err != nil {
		return nil, fmt.Errorf("error preparing query GetGrossProfitSummary: %w", err)
	}
	if q.getMenusByUserIDStmt, err = db.PrepareContext(ctx, getMenusByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetMenusByUserID: %w", err)
	}
	if q.getPaymentByIDStmt, err = db.PrepareContext(ctx, getPaymentByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPaymentByID: %w", err)
	}
	if q.getProductByCodeStmt, err = db.PrepareContext(ctx, getProductByCode); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductByCode: %w", err)
	}
	if q.getProductByIDStmt, err = db.PrepareContext(ctx, getProductByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductByID: %w", err)
	}
	if q.getPurchaseOrderByIDStmt, err = db.PrepareContext(ctx, getPurchaseOrderByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPurchaseOrderByID: %w", err)
	}
	if q.getPurchaseOrderLinesStmt, err = db.PrepareContext(ctx, getPurchaseOrderLines); err != nil {
		return nil, fmt.Errorf("error preparing query GetPurchaseOrderLines: %w", err)
	}
	if q.getQuotationByIDStmt, err = db.PrepareContext(ctx, getQuotationByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetQuotationByID: %w", err)
	}
	if q.getQuotationLinesStmt, err = db.PrepareContext(ctx, getQuotationLines); err != nil {
		return nil, fmt.Errorf("error preparing query GetQuotationLines: %w", err)
	}
	if q.getRoleByCodeStmt, err = db.PrepareContext(ctx, getRoleByCode); err != nil {
		return nil, fmt.Errorf("error preparing query GetRoleByCode: %w", err)
	}
	if q.getSalesOrderByIDStmt, err = db.PrepareContext(ctx, getSalesOrderByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSalesOrderByID: %w", err)
	}
	if q.getSalesOrderLinesStmt, err = db.PrepareContext(ctx, getSalesOrderLines); err != nil {
		return nil, fmt.Errorf("error preparing query GetSalesOrderLines: %w", err)
	}
	if q.getStockAdjustmentByIDStmt, err = db.PrepareContext(ctx, getStockAdjustmentByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetStockAdjustmentByID: %w", err)
	}
	if q.getStockAdjustmentLinesStmt, err = db.PrepareContext(ctx, getStockAdjustmentLines); err != nil {
		return nil, fmt.Errorf("error preparing query GetStockAdjustmentLines: %w", err)
	}
	if q.getStockBalanceStmt, err = db.PrepareContext(ctx, getStockBalance); err != nil {
		return nil, fmt.Errorf("error preparing query GetStockBalance: %w", err)
	}
	if q.getSupplierBillByIDStmt, err = db.PrepareContext(ctx, getSupplierBillByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSupplierBillByID: %w", err)
	}
	if q.getSupplierByIDStmt, err = db.PrepareContext(ctx, getSupplierByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSupplierByID: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.getUserByUsernameStmt, err = db.PrepareContext(ctx, getUserByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByUsername: %w", err)
	}
	if q.getUserRolesStmt, err = db.PrepareContext(ctx, getUserRoles); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserRoles: %w", err)
	}
	if q.listActiveCategoriesStmt, err = db.PrepareContext(ctx, listActiveCategories); err != nil {
		return nil, fmt.Errorf("error preparing query ListActiveCategories: %w", err)
	}
	if q.listActiveCustomersStmt, err = db.PrepareContext(ctx, listActiveCustomers); err != nil {
		return nil, fmt.Errorf("error preparing query ListActiveCustomers: %w", err)
	}
	if q.listActiveProductsStmt, err = db.PrepareContext(ctx, listActiveProducts); err != nil {
		return nil, fmt.Errorf("error preparing query ListActiveProducts: %w", err)
	}
	if q.listActiveStockLocationsStmt, err = db.PrepareContext(ctx, listActiveStockLocations); err != nil {
		return nil, fmt.Errorf("error preparing query ListActiveStockLocations: %w", err)
	}
	if q.listActiveSuppliersStmt, err = db.PrepareContext(ctx, listActiveSuppliers); err != nil {
		return nil, fmt.Errorf("error preparing query ListActiveSuppliers: %w", err)
	}
	if q.listActiveUoMStmt, err = db.PrepareContext(ctx, listActiveUoM); err != nil {
		return nil, fmt.Errorf("error preparing query ListActiveUoM: %w", err)
	}
	if q.listActiveUsersStmt, err = db.PrepareContext(ctx, listActiveUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListActiveUsers: %w", err)
	}
	if q.listCustomerInvoicesStmt, err = db.PrepareContext(ctx, listCustomerInvoices); err != nil {
		return nil, fmt.Errorf("error preparing query ListCustomerInvoices: %w", err)
	}
	if q.listPaymentsStmt, err = db.PrepareContext(ctx, listPayments); err != nil {
		return nil, fmt.Errorf("error preparing query ListPayments: %w", err)
	}
	if q.listPurchaseOrdersStmt, err = db.PrepareContext(ctx, listPurchaseOrders); err != nil {
		return nil, fmt.Errorf("error preparing query ListPurchaseOrders: %w", err)
	}
	if q.listQuotationsStmt, err = db.PrepareContext(ctx, listQuotations); err != nil {
		return nil, fmt.Errorf("error preparing query ListQuotations: %w", err)
	}
	if q.listSalesOrdersStmt, err = db.PrepareContext(ctx, listSalesOrders); err != nil {
		return nil, fmt.Errorf("error preparing query ListSalesOrders: %w", err)
	}
	if q.listStockAdjustmentsStmt, err = db.PrepareContext(ctx, listStockAdjustments); err != nil {
		return nil, fmt.Errorf("error preparing query ListStockAdjustments: %w", err)
	}
	if q.listStockBalancesStmt, err = db.PrepareContext(ctx, listStockBalances); err != nil {
		return nil, fmt.Errorf("error preparing query ListStockBalances: %w", err)
	}
	if q.listStockMovementsStmt, err = db.PrepareContext(ctx, listStockMovements); err != nil {
		return nil, fmt.Errorf("error preparing query ListStockMovements: %w", err)
	}
	if q.listSupplierBillsStmt, err = db.PrepareContext(ctx, listSupplierBills); err != nil {
		return nil, fmt.Errorf("error preparing query ListSupplierBills: %w", err)
	}
	if q.updateCustomerStmt, err = db.PrepareContext(ctx, updateCustomer); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCustomer: %w", err)
	}
	if q.updateCustomerInvoicePaidAmountStmt, err = db.PrepareContext(ctx, updateCustomerInvoicePaidAmount); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCustomerInvoicePaidAmount: %w", err)
	}
	if q.updatePOLineReceivedQtyStmt, err = db.PrepareContext(ctx, updatePOLineReceivedQty); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePOLineReceivedQty: %w", err)
	}
	if q.updateProductStmt, err = db.PrepareContext(ctx, updateProduct); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProduct: %w", err)
	}
	if q.updatePurchaseOrderStatusStmt, err = db.PrepareContext(ctx, updatePurchaseOrderStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePurchaseOrderStatus: %w", err)
	}
	if q.updateQuotationStatusStmt, err = db.PrepareContext(ctx, updateQuotationStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateQuotationStatus: %w", err)
	}
	if q.updateSOLineDeliveredQtyStmt, err = db.PrepareContext(ctx, updateSOLineDeliveredQty); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSOLineDeliveredQty: %w", err)
	}
	if q.updateSalesOrderStatusStmt, err = db.PrepareContext(ctx, updateSalesOrderStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSalesOrderStatus: %w", err)
	}
	if q.updateStockAdjustmentStatusStmt, err = db.PrepareContext(ctx, updateStockAdjustmentStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateStockAdjustmentStatus: %w", err)
	}
	if q.updateStockQuantityStmt, err = db.PrepareContext(ctx, updateStockQuantity); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateStockQuantity: %w", err)
	}
	if q.updateSupplierStmt, err = db.PrepareContext(ctx, updateSupplier); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSupplier: %w", err)
	}
	if q.updateSupplierBillPaidAmountStmt, err = db.PrepareContext(ctx, updateSupplierBillPaidAmount); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSupplierBillPaidAmount: %w", err)
	}
	if q.updateUserLastLoginStmt, err = db.PrepareContext(ctx, updateUserLastLogin); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserLastLogin: %w", err)
	}
	if q.upsertStockBalanceStmt, err = db.PrepareContext(ctx, upsertStockBalance); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertStockBalance: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.assignRoleToUserStmt != nil {
		if cerr := q.assignRoleToUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing assignRoleToUserStmt: %w", cerr)
		}
	}
	if q.checkUserMenuAccessStmt != nil {
		if cerr := q.checkUserMenuAccessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkUserMenuAccessStmt: %w", cerr)
		}
	}
	if q.createCategoryStmt != nil {
		if cerr := q.createCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCategoryStmt: %w", cerr)
		}
	}
	if q.createCustomerStmt != nil {
		if cerr := q.createCustomerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCustomerStmt: %w", cerr)
		}
	}
	if q.createCustomerInvoiceStmt != nil {
		if cerr := q.createCustomerInvoiceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCustomerInvoiceStmt: %w", cerr)
		}
	}
	if q.createGoodsReceiptStmt != nil {
		if cerr := q.createGoodsReceiptStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createGoodsReceiptStmt: %w", cerr)
		}
	}
	if q.createGoodsReceiptLineStmt != nil {
		if cerr := q.createGoodsReceiptLineStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createGoodsReceiptLineStmt: %w", cerr)
		}
	}
	if q.createPaymentStmt != nil {
		if cerr := q.createPaymentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPaymentStmt: %w", cerr)
		}
	}
	if q.createProductStmt != nil {
		if cerr := q.createProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProductStmt: %w", cerr)
		}
	}
	if q.createPurchaseOrderStmt != nil {
		if cerr := q.createPurchaseOrderStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPurchaseOrderStmt: %w", cerr)
		}
	}
	if q.createPurchaseOrderLineStmt != nil {
		if cerr := q.createPurchaseOrderLineStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPurchaseOrderLineStmt: %w", cerr)
		}
	}
	if q.createQuotationStmt != nil {
		if cerr := q.createQuotationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createQuotationStmt: %w", cerr)
		}
	}
	if q.createQuotationLineStmt != nil {
		if cerr := q.createQuotationLineStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createQuotationLineStmt: %w", cerr)
		}
	}
	if q.createSalesOrderStmt != nil {
		if cerr := q.createSalesOrderStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSalesOrderStmt: %w", cerr)
		}
	}
	if q.createSalesOrderLineStmt != nil {
		if cerr := q.createSalesOrderLineStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSalesOrderLineStmt: %w", cerr)
		}
	}
	if q.createStockAdjustmentStmt != nil {
		if cerr := q.createStockAdjustmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createStockAdjustmentStmt: %w", cerr)
		}
	}
	if q.createStockAdjustmentLineStmt != nil {
		if cerr := q.createStockAdjustmentLineStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createStockAdjustmentLineStmt: %w", cerr)
		}
	}
	if q.createStockLocationStmt != nil {
		if cerr := q.createStockLocationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createStockLocationStmt: %w", cerr)
		}
	}
	if q.createStockMovementStmt != nil {
		if cerr := q.createStockMovementStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createStockMovementStmt: %w", cerr)
		}
	}
	if q.createSupplierStmt != nil {
		if cerr := q.createSupplierStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSupplierStmt: %w", cerr)
		}
	}
	if q.createSupplierBillStmt != nil {
		if cerr := q.createSupplierBillStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSupplierBillStmt: %w", cerr)
		}
	}
	if q.createUnitOfMeasureStmt != nil {
		if cerr := q.createUnitOfMeasureStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUnitOfMeasureStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.getAccountsPayableSummaryStmt != nil {
		if cerr := q.getAccountsPayableSummaryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountsPayableSummaryStmt: %w", cerr)
		}
	}
	if q.getAccountsReceivableSummaryStmt != nil {
		if cerr := q.getAccountsReceivableSummaryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountsReceivableSummaryStmt: %w", cerr)
		}
	}
	if q.getAgingReceivablesStmt != nil {
		if cerr := q.getAgingReceivablesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAgingReceivablesStmt: %w", cerr)
		}
	}
	if q.getCashFlowSummaryStmt != nil {
		if cerr := q.getCashFlowSummaryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCashFlowSummaryStmt: %w", cerr)
		}
	}
	if q.getCategoryByIDStmt != nil {
		if cerr := q.getCategoryByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCategoryByIDStmt: %w", cerr)
		}
	}
	if q.getCustomerByIDStmt != nil {
		if cerr := q.getCustomerByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCustomerByIDStmt: %w", cerr)
		}
	}
	if q.getCustomerInvoiceByIDStmt != nil {
		if cerr := q.getCustomerInvoiceByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCustomerInvoiceByIDStmt: %w", cerr)
		}
	}
	if q.getGoodsReceiptsByPOStmt != nil {
		if cerr := q.getGoodsReceiptsByPOStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGoodsReceiptsByPOStmt: %w", cerr)
		}
	}
	if q.getGrossProfitByProductStmt != nil {
		if cerr := q.getGrossProfitByProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGrossProfitByProductStmt: %w", cerr)
		}
	}
	if q.getGrossProfitSummaryStmt != nil {
		if cerr := q.getGrossProfitSummaryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGrossProfitSummaryStmt: %w", cerr)
		}
	}
	if q.getMenusByUserIDStmt != nil {
		if cerr := q.getMenusByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMenusByUserIDStmt: %w", cerr)
		}
	}
	if q.getPaymentByIDStmt != nil {
		if cerr := q.getPaymentByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPaymentByIDStmt: %w", cerr)
		}
	}
	if q.getProductByCodeStmt != nil {
		if cerr := q.getProductByCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductByCodeStmt: %w", cerr)
		}
	}
	if q.getProductByIDStmt != nil {
		if cerr := q.getProductByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductByIDStmt: %w", cerr)
		}
	}
	if q.getPurchaseOrderByIDStmt != nil {
		if cerr := q.getPurchaseOrderByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPurchaseOrderByIDStmt: %w", cerr)
		}
	}
	if q.getPurchaseOrderLinesStmt != nil {
		if cerr := q.getPurchaseOrderLinesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPurchaseOrderLinesStmt: %w", cerr)
		}
	}
	if q.getQuotationByIDStmt != nil {
		if cerr := q.getQuotationByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getQuotationByIDStmt: %w", cerr)
		}
	}
	if q.getQuotationLinesStmt != nil {
		if cerr := q.getQuotationLinesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getQuotationLinesStmt: %w", cerr)
		}
	}
	if q.getRoleByCodeStmt != nil {
		if cerr := q.getRoleByCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRoleByCodeStmt: %w", cerr)
		}
	}
	if q.getSalesOrderByIDStmt != nil {
		if cerr := q.getSalesOrderByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSalesOrderByIDStmt: %w", cerr)
		}
	}
	if q.getSalesOrderLinesStmt != nil {
		if cerr := q.getSalesOrderLinesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSalesOrderLinesStmt: %w", cerr)
		}
	}
	if q.getStockAdjustmentByIDStmt != nil {
		if cerr := q.getStockAdjustmentByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStockAdjustmentByIDStmt: %w", cerr)
		}
	}
	if q.getStockAdjustmentLinesStmt != nil {
		if cerr := q.getStockAdjustmentLinesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStockAdjustmentLinesStmt: %w", cerr)
		}
	}
	if q.getStockBalanceStmt != nil {
		if cerr := q.getStockBalanceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStockBalanceStmt: %w", cerr)
		}
	}
	if q.getSupplierBillByIDStmt != nil {
		if cerr := q.getSupplierBillByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSupplierBillByIDStmt: %w", cerr)
		}
	}
	if q.getSupplierByIDStmt != nil {
		if cerr := q.getSupplierByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSupplierByIDStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.getUserByUsernameStmt != nil {
		if cerr := q.getUserByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByUsernameStmt: %w", cerr)
		}
	}
	if q.getUserRolesStmt != nil {
		if cerr := q.getUserRolesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserRolesStmt: %w", cerr)
		}
	}
	if q.listActiveCategoriesStmt != nil {
		if cerr := q.listActiveCategoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listActiveCategoriesStmt: %w", cerr)
		}
	}
	if q.listActiveCustomersStmt != nil {
		if cerr := q.listActiveCustomersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listActiveCustomersStmt: %w", cerr)
		}
	}
	if q.listActiveProductsStmt != nil {
		if cerr := q.listActiveProductsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listActiveProductsStmt: %w", cerr)
		}
	}
	if q.listActiveStockLocationsStmt != nil {
		if cerr := q.listActiveStockLocationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listActiveStockLocationsStmt: %w", cerr)
		}
	}
	if q.listActiveSuppliersStmt != nil {
		if cerr := q.listActiveSuppliersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listActiveSuppliersStmt: %w", cerr)
		}
	}
	if q.listActiveUoMStmt != nil {
		if cerr := q.listActiveUoMStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listActiveUoMStmt: %w", cerr)
		}
	}
	if q.listActiveUsersStmt != nil {
		if cerr := q.listActiveUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listActiveUsersStmt: %w", cerr)
		}
	}
	if q.listCustomerInvoicesStmt != nil {
		if cerr := q.listCustomerInvoicesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCustomerInvoicesStmt: %w", cerr)
		}
	}
	if q.listPaymentsStmt != nil {
		if cerr := q.listPaymentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPaymentsStmt: %w", cerr)
		}
	}
	if q.listPurchaseOrdersStmt != nil {
		if cerr := q.listPurchaseOrdersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPurchaseOrdersStmt: %w", cerr)
		}
	}
	if q.listQuotationsStmt != nil {
		if cerr := q.listQuotationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listQuotationsStmt: %w", cerr)
		}
	}
	if q.listSalesOrdersStmt != nil {
		if cerr := q.listSalesOrdersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSalesOrdersStmt: %w", cerr)
		}
	}
	if q.listStockAdjustmentsStmt != nil {
		if cerr := q.listStockAdjustmentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listStockAdjustmentsStmt: %w", cerr)
		}
	}
	if q.listStockBalancesStmt != nil {
		if cerr := q.listStockBalancesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listStockBalancesStmt: %w", cerr)
		}
	}
	if q.listStockMovementsStmt != nil {
		if cerr := q.listStockMovementsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listStockMovementsStmt: %w", cerr)
		}
	}
	if q.listSupplierBillsStmt != nil {
		if cerr := q.listSupplierBillsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSupplierBillsStmt: %w", cerr)
		}
	}
	if q.updateCustomerStmt != nil {
		if cerr := q.updateCustomerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCustomerStmt: %w", cerr)
		}
	}
	if q.updateCustomerInvoicePaidAmountStmt != nil {
		if cerr := q.updateCustomerInvoicePaidAmountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCustomerInvoicePaidAmountStmt: %w", cerr)
		}
	}
	if q.updatePOLineReceivedQtyStmt != nil {
		if cerr := q.updatePOLineReceivedQtyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePOLineReceivedQtyStmt: %w", cerr)
		}
	}
	if q.updateProductStmt != nil {
		if cerr := q.updateProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProductStmt: %w", cerr)
		}
	}
	if q.updatePurchaseOrderStatusStmt != nil {
		if cerr := q.updatePurchaseOrderStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePurchaseOrderStatusStmt: %w", cerr)
		}
	}
	if q.updateQuotationStatusStmt != nil {
		if cerr := q.updateQuotationStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateQuotationStatusStmt: %w", cerr)
		}
	}
	if q.updateSOLineDeliveredQtyStmt != nil {
		if cerr := q.updateSOLineDeliveredQtyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSOLineDeliveredQtyStmt: %w", cerr)
		}
	}
	if q.updateSalesOrderStatusStmt != nil {
		if cerr := q.updateSalesOrderStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSalesOrderStatusStmt: %w", cerr)
		}
	}
	if q.updateStockAdjustmentStatusStmt != nil {
		if cerr := q.updateStockAdjustmentStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateStockAdjustmentStatusStmt: %w", cerr)
		}
	}
	if q.updateStockQuantityStmt != nil {
		if cerr := q.updateStockQuantityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateStockQuantityStmt: %w", cerr)
		}
	}
	if q.updateSupplierStmt != nil {
		if cerr := q.updateSupplierStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSupplierStmt: %w", cerr)
		}
	}
	if q.updateSupplierBillPaidAmountStmt != nil {
		if cerr := q.updateSupplierBillPaidAmountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSupplierBillPaidAmountStmt: %w", cerr)
		}
	}
	if q.updateUserLastLoginStmt != nil {
		if cerr := q.updateUserLastLoginStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserLastLoginStmt: %w", cerr)
		}
	}
	if q.upsertStockBalanceStmt != nil {
		if cerr := q.upsertStockBalanceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertStockBalanceStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                  DBTX
	tx                                  *sql.Tx
	assignRoleToUserStmt                *sql.Stmt
	checkUserMenuAccessStmt             *sql.Stmt
	createCategoryStmt                  *sql.Stmt
	createCustomerStmt                  *sql.Stmt
	createCustomerInvoiceStmt           *sql.Stmt
	createGoodsReceiptStmt              *sql.Stmt
	createGoodsReceiptLineStmt          *sql.Stmt
	createPaymentStmt                   *sql.Stmt
	createProductStmt                   *sql.Stmt
	createPurchaseOrderStmt             *sql.Stmt
	createPurchaseOrderLineStmt         *sql.Stmt
	createQuotationStmt                 *sql.Stmt
	createQuotationLineStmt             *sql.Stmt
	createSalesOrderStmt                *sql.Stmt
	createSalesOrderLineStmt            *sql.Stmt
	createStockAdjustmentStmt           *sql.Stmt
	createStockAdjustmentLineStmt       *sql.Stmt
	createStockLocationStmt             *sql.Stmt
	createStockMovementStmt             *sql.Stmt
	createSupplierStmt                  *sql.Stmt
	createSupplierBillStmt              *sql.Stmt
	createUnitOfMeasureStmt             *sql.Stmt
	createUserStmt                      *sql.Stmt
	getAccountsPayableSummaryStmt       *sql.Stmt
	getAccountsReceivableSummaryStmt    *sql.Stmt
	getAgingReceivablesStmt             *sql.Stmt
	getCashFlowSummaryStmt              *sql.Stmt
	getCategoryByIDStmt                 *sql.Stmt
	getCustomerByIDStmt                 *sql.Stmt
	getCustomerInvoiceByIDStmt          *sql.Stmt
	getGoodsReceiptsByPOStmt            *sql.Stmt
	getGrossProfitByProductStmt         *sql.Stmt
	getGrossProfitSummaryStmt           *sql.Stmt
	getMenusByUserIDStmt                *sql.Stmt
	getPaymentByIDStmt                  *sql.Stmt
	getProductByCodeStmt                *sql.Stmt
	getProductByIDStmt                  *sql.Stmt
	getPurchaseOrderByIDStmt            *sql.Stmt
	getPurchaseOrderLinesStmt           *sql.Stmt
	getQuotationByIDStmt                *sql.Stmt
	getQuotationLinesStmt               *sql.Stmt
	getRoleByCodeStmt                   *sql.Stmt
	getSalesOrderByIDStmt               *sql.Stmt
	getSalesOrderLinesStmt              *sql.Stmt
	getStockAdjustmentByIDStmt          *sql.Stmt
	getStockAdjustmentLinesStmt         *sql.Stmt
	getStockBalanceStmt                 *sql.Stmt
	getSupplierBillByIDStmt             *sql.Stmt
	getSupplierByIDStmt                 *sql.Stmt
	getUserByIDStmt                     *sql.Stmt
	getUserByUsernameStmt               *sql.Stmt
	getUserRolesStmt                    *sql.Stmt
	listActiveCategoriesStmt            *sql.Stmt
	listActiveCustomersStmt             *sql.Stmt
	listActiveProductsStmt              *sql.Stmt
	listActiveStockLocationsStmt        *sql.Stmt
	listActiveSuppliersStmt             *sql.Stmt
	listActiveUoMStmt                   *sql.Stmt
	listActiveUsersStmt                 *sql.Stmt
	listCustomerInvoicesStmt            *sql.Stmt
	listPaymentsStmt                    *sql.Stmt
	listPurchaseOrdersStmt              *sql.Stmt
	listQuotationsStmt                  *sql.Stmt
	listSalesOrdersStmt                 *sql.Stmt
	listStockAdjustmentsStmt            *sql.Stmt
	listStockBalancesStmt               *sql.Stmt
	listStockMovementsStmt              *sql.Stmt
	listSupplierBillsStmt               *sql.Stmt
	updateCustomerStmt                  *sql.Stmt
	updateCustomerInvoicePaidAmountStmt *sql.Stmt
	updatePOLineReceivedQtyStmt         *sql.Stmt
	updateProductStmt                   *sql.Stmt
	updatePurchaseOrderStatusStmt       *sql.Stmt
	updateQuotationStatusStmt           *sql.Stmt
	updateSOLineDeliveredQtyStmt        *sql.Stmt
	updateSalesOrderStatusStmt          *sql.Stmt
	updateStockAdjustmentStatusStmt     *sql.Stmt
	updateStockQuantityStmt             *sql.Stmt
	updateSupplierStmt                  *sql.Stmt
	updateSupplierBillPaidAmountStmt    *sql.Stmt
	updateUserLastLoginStmt             *sql.Stmt
	upsertStockBalanceStmt              *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                  tx,
		tx:                                  tx,
		assignRoleToUserStmt:                q.assignRoleToUserStmt,
		checkUserMenuAccessStmt:             q.checkUserMenuAccessStmt,
		createCategoryStmt:                  q.createCategoryStmt,
		createCustomerStmt:                  q.createCustomerStmt,
		createCustomerInvoiceStmt:           q.createCustomerInvoiceStmt,
		createGoodsReceiptStmt:              q.createGoodsReceiptStmt,
		createGoodsReceiptLineStmt:          q.createGoodsReceiptLineStmt,
		createPaymentStmt:                   q.createPaymentStmt,
		createProductStmt:                   q.createProductStmt,
		createPurchaseOrderStmt:             q.createPurchaseOrderStmt,
		createPurchaseOrderLineStmt:         q.createPurchaseOrderLineStmt,
		createQuotationStmt:                 q.createQuotationStmt,
		createQuotationLineStmt:             q.createQuotationLineStmt,
		createSalesOrderStmt:                q.createSalesOrderStmt,
		createSalesOrderLineStmt:            q.createSalesOrderLineStmt,
		createStockAdjustmentStmt:           q.createStockAdjustmentStmt,
		createStockAdjustmentLineStmt:       q.createStockAdjustmentLineStmt,
		createStockLocationStmt:             q.createStockLocationStmt,
		createStockMovementStmt:             q.createStockMovementStmt,
		createSupplierStmt:                  q.createSupplierStmt,
		createSupplierBillStmt:              q.createSupplierBillStmt,
		createUnitOfMeasureStmt:             q.createUnitOfMeasureStmt,
		createUserStmt:                      q.createUserStmt,
		getAccountsPayableSummaryStmt:       q.getAccountsPayableSummaryStmt,
		getAccountsReceivableSummaryStmt:    q.getAccountsReceivableSummaryStmt,
		getAgingReceivablesStmt:             q.getAgingReceivablesStmt,
		getCashFlowSummaryStmt:              q.getCashFlowSummaryStmt,
		getCategoryByIDStmt:                 q.getCategoryByIDStmt,
		getCustomerByIDStmt:                 q.getCustomerByIDStmt,
		getCustomerInvoiceByIDStmt:          q.getCustomerInvoiceByIDStmt,
		getGoodsReceiptsByPOStmt:            q.getGoodsReceiptsByPOStmt,
		getGrossProfitByProductStmt:         q.getGrossProfitByProductStmt,
		getGrossProfitSummaryStmt:           q.getGrossProfitSummaryStmt,
		getMenusByUserIDStmt:                q.getMenusByUserIDStmt,
		getPaymentByIDStmt:                  q.getPaymentByIDStmt,
		getProductByCodeStmt:                q.getProductByCodeStmt,
		getProductByIDStmt:                  q.getProductByIDStmt,
		getPurchaseOrderByIDStmt:            q.getPurchaseOrderByIDStmt,
		getPurchaseOrderLinesStmt:           q.getPurchaseOrderLinesStmt,
		getQuotationByIDStmt:                q.getQuotationByIDStmt,
		getQuotationLinesStmt:               q.getQuotationLinesStmt,
		getRoleByCodeStmt:                   q.getRoleByCodeStmt,
		getSalesOrderByIDStmt:               q.getSalesOrderByIDStmt,
		getSalesOrderLinesStmt:              q.getSalesOrderLinesStmt,
		getStockAdjustmentByIDStmt:          q.getStockAdjustmentByIDStmt,
		getStockAdjustmentLinesStmt:         q.getStockAdjustmentLinesStmt,
		getStockBalanceStmt:                 q.getStockBalanceStmt,
		getSupplierBillByIDStmt:             q.getSupplierBillByIDStmt,
		getSupplierByIDStmt:                 q.getSupplierByIDStmt,
		getUserByIDStmt:                     q.getUserByIDStmt,
		getUserByUsernameStmt:               q.getUserByUsernameStmt,
		getUserRolesStmt:                    q.getUserRolesStmt,
		listActiveCategoriesStmt:            q.listActiveCategoriesStmt,
		listActiveCustomersStmt:             q.listActiveCustomersStmt,
		listActiveProductsStmt:              q.listActiveProductsStmt,
		listActiveStockLocationsStmt:        q.listActiveStockLocationsStmt,
		listActiveSuppliersStmt:             q.listActiveSuppliersStmt,
		listActiveUoMStmt:                   q.listActiveUoMStmt,
		listActiveUsersStmt:                 q.listActiveUsersStmt,
		listCustomerInvoicesStmt:            q.listCustomerInvoicesStmt,
		listPaymentsStmt:                    q.listPaymentsStmt,
		listPurchaseOrdersStmt:              q.listPurchaseOrdersStmt,
		listQuotationsStmt:                  q.listQuotationsStmt,
		listSalesOrdersStmt:                 q.listSalesOrdersStmt,
		listStockAdjustmentsStmt:            q.listStockAdjustmentsStmt,
		listStockBalancesStmt:               q.listStockBalancesStmt,
		listStockMovementsStmt:              q.listStockMovementsStmt,
		listSupplierBillsStmt:               q.listSupplierBillsStmt,
		updateCustomerStmt:                  q.updateCustomerStmt,
		updateCustomerInvoicePaidAmountStmt: q.updateCustomerInvoicePaidAmountStmt,
		updatePOLineReceivedQtyStmt:         q.updatePOLineReceivedQtyStmt,
		updateProductStmt:                   q.updateProductStmt,
		updatePurchaseOrderStatusStmt:       q.updatePurchaseOrderStatusStmt,
		updateQuotationStatusStmt:           q.updateQuotationStatusStmt,
		updateSOLineDeliveredQtyStmt:        q.updateSOLineDeliveredQtyStmt,
		updateSalesOrderStatusStmt:          q.updateSalesOrderStatusStmt,
		updateStockAdjustmentStatusStmt:     q.updateStockAdjustmentStatusStmt,
		updateStockQuantityStmt:             q.updateStockQuantityStmt,
		updateSupplierStmt:                  q.updateSupplierStmt,
		updateSupplierBillPaidAmountStmt:    q.updateSupplierBillPaidAmountStmt,
		updateUserLastLoginStmt:             q.updateUserLastLoginStmt,
		upsertStockBalanceStmt:              q.upsertStockBalanceStmt,
	}
}
