// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID        uuid.UUID             `json:"id"`
	UserID    uuid.NullUUID         `json:"user_id"`
	TableName string                `json:"table_name"`
	RecordID  uuid.UUID             `json:"record_id"`
	Action    string                `json:"action"`
	OldValues pqtype.NullRawMessage `json:"old_values"`
	NewValues pqtype.NullRawMessage `json:"new_values"`
	IpAddress pqtype.Inet           `json:"ip_address"`
	UserAgent sql.NullString        `json:"user_agent"`
	CreatedAt sql.NullTime          `json:"created_at"`
}

type Category struct {
	ID          uuid.UUID      `json:"id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ParentID    uuid.NullUUID  `json:"parent_id"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Customer struct {
	ID            uuid.UUID      `json:"id"`
	Code          string         `json:"code"`
	Name          string         `json:"name"`
	ContactPerson sql.NullString `json:"contact_person"`
	Email         sql.NullString `json:"email"`
	Phone         sql.NullString `json:"phone"`
	Address       sql.NullString `json:"address"`
	TaxID         sql.NullString `json:"tax_id"`
	CreditLimit   sql.NullString `json:"credit_limit"`
	PaymentTerms  sql.NullInt32  `json:"payment_terms"`
	IsActive      sql.NullBool   `json:"is_active"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
}

type CustomerInvoice struct {
	ID            uuid.UUID      `json:"id"`
	InvoiceNumber string         `json:"invoice_number"`
	CustomerID    uuid.UUID      `json:"customer_id"`
	SoID          uuid.NullUUID  `json:"so_id"`
	InvoiceDate   time.Time      `json:"invoice_date"`
	DueDate       time.Time      `json:"due_date"`
	TotalAmount   string         `json:"total_amount"`
	PaidAmount    sql.NullString `json:"paid_amount"`
	Status        sql.NullString `json:"status"`
	Notes         sql.NullString `json:"notes"`
	CreatedBy     uuid.NullUUID  `json:"created_by"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type GoodsReceipt struct {
	ID            uuid.UUID      `json:"id"`
	ReceiptNumber string         `json:"receipt_number"`
	PoID          uuid.UUID      `json:"po_id"`
	ReceiptDate   time.Time      `json:"receipt_date"`
	Notes         sql.NullString `json:"notes"`
	ReceivedBy    uuid.NullUUID  `json:"received_by"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type GoodsReceiptLine struct {
	ID         uuid.UUID    `json:"id"`
	ReceiptID  uuid.UUID    `json:"receipt_id"`
	PoLineID   uuid.UUID    `json:"po_line_id"`
	ProductID  uuid.UUID    `json:"product_id"`
	Quantity   string       `json:"quantity"`
	LineNumber int32        `json:"line_number"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type Menu struct {
	ID        uuid.UUID      `json:"id"`
	ParentID  uuid.NullUUID  `json:"parent_id"`
	Code      string         `json:"code"`
	Name      string         `json:"name"`
	Path      sql.NullString `json:"path"`
	Icon      sql.NullString `json:"icon"`
	SortOrder sql.NullInt32  `json:"sort_order"`
	IsActive  sql.NullBool   `json:"is_active"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Payment struct {
	ID            uuid.UUID      `json:"id"`
	PaymentNumber string         `json:"payment_number"`
	PaymentType   string         `json:"payment_type"`
	PartnerType   string         `json:"partner_type"`
	PartnerID     uuid.UUID      `json:"partner_id"`
	InvoiceID     uuid.NullUUID  `json:"invoice_id"`
	PaymentDate   time.Time      `json:"payment_date"`
	Amount        string         `json:"amount"`
	PaymentMethod sql.NullString `json:"payment_method"`
	Reference     sql.NullString `json:"reference"`
	Notes         sql.NullString `json:"notes"`
	CreatedBy     uuid.NullUUID  `json:"created_by"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type Product struct {
	ID          uuid.UUID      `json:"id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CategoryID  uuid.NullUUID  `json:"category_id"`
	UomID       uuid.UUID      `json:"uom_id"`
	ProductType sql.NullString `json:"product_type"`
	CostPrice   sql.NullString `json:"cost_price"`
	SalePrice   sql.NullString `json:"sale_price"`
	MinStock    sql.NullString `json:"min_stock"`
	MaxStock    sql.NullString `json:"max_stock"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type PurchaseOrder struct {
	ID           uuid.UUID      `json:"id"`
	PoNumber     string         `json:"po_number"`
	SupplierID   uuid.UUID      `json:"supplier_id"`
	OrderDate    time.Time      `json:"order_date"`
	ExpectedDate sql.NullTime   `json:"expected_date"`
	Status       sql.NullString `json:"status"`
	TotalAmount  sql.NullString `json:"total_amount"`
	Notes        sql.NullString `json:"notes"`
	CreatedBy    uuid.NullUUID  `json:"created_by"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type PurchaseOrderLine struct {
	ID          uuid.UUID      `json:"id"`
	PoID        uuid.UUID      `json:"po_id"`
	ProductID   uuid.UUID      `json:"product_id"`
	Quantity    string         `json:"quantity"`
	UnitPrice   string         `json:"unit_price"`
	Subtotal    sql.NullString `json:"subtotal"`
	ReceivedQty sql.NullString `json:"received_qty"`
	LineNumber  int32          `json:"line_number"`
	Notes       sql.NullString `json:"notes"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Quotation struct {
	ID          uuid.UUID      `json:"id"`
	QuoteNumber string         `json:"quote_number"`
	CustomerID  uuid.UUID      `json:"customer_id"`
	QuoteDate   time.Time      `json:"quote_date"`
	ValidUntil  sql.NullTime   `json:"valid_until"`
	Status      sql.NullString `json:"status"`
	TotalAmount sql.NullString `json:"total_amount"`
	Notes       sql.NullString `json:"notes"`
	CreatedBy   uuid.NullUUID  `json:"created_by"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type QuotationLine struct {
	ID         uuid.UUID      `json:"id"`
	QuoteID    uuid.UUID      `json:"quote_id"`
	ProductID  uuid.UUID      `json:"product_id"`
	Quantity   string         `json:"quantity"`
	UnitPrice  string         `json:"unit_price"`
	Subtotal   sql.NullString `json:"subtotal"`
	LineNumber int32          `json:"line_number"`
	Notes      sql.NullString `json:"notes"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type Role struct {
	ID          uuid.UUID      `json:"id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type RoleMenu struct {
	ID        uuid.UUID    `json:"id"`
	RoleID    uuid.UUID    `json:"role_id"`
	MenuID    uuid.UUID    `json:"menu_id"`
	CanCreate sql.NullBool `json:"can_create"`
	CanRead   sql.NullBool `json:"can_read"`
	CanUpdate sql.NullBool `json:"can_update"`
	CanDelete sql.NullBool `json:"can_delete"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type SalesOrder struct {
	ID           uuid.UUID      `json:"id"`
	SoNumber     string         `json:"so_number"`
	CustomerID   uuid.UUID      `json:"customer_id"`
	QuoteID      uuid.NullUUID  `json:"quote_id"`
	OrderDate    time.Time      `json:"order_date"`
	DeliveryDate sql.NullTime   `json:"delivery_date"`
	Status       sql.NullString `json:"status"`
	TotalAmount  sql.NullString `json:"total_amount"`
	Notes        sql.NullString `json:"notes"`
	CreatedBy    uuid.NullUUID  `json:"created_by"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type SalesOrderLine struct {
	ID           uuid.UUID      `json:"id"`
	SoID         uuid.UUID      `json:"so_id"`
	ProductID    uuid.UUID      `json:"product_id"`
	Quantity     string         `json:"quantity"`
	UnitPrice    string         `json:"unit_price"`
	Subtotal     sql.NullString `json:"subtotal"`
	DeliveredQty sql.NullString `json:"delivered_qty"`
	LineNumber   int32          `json:"line_number"`
	Notes        sql.NullString `json:"notes"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type StockAdjustment struct {
	ID               uuid.UUID      `json:"id"`
	AdjustmentNumber string         `json:"adjustment_number"`
	LocationID       uuid.UUID      `json:"location_id"`
	AdjustmentDate   time.Time      `json:"adjustment_date"`
	Reason           sql.NullString `json:"reason"`
	Status           sql.NullString `json:"status"`
	CreatedBy        uuid.NullUUID  `json:"created_by"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

type StockAdjustmentLine struct {
	ID             uuid.UUID      `json:"id"`
	AdjustmentID   uuid.UUID      `json:"adjustment_id"`
	ProductID      uuid.UUID      `json:"product_id"`
	QuantityBefore string         `json:"quantity_before"`
	QuantityAfter  string         `json:"quantity_after"`
	Difference     sql.NullString `json:"difference"`
	LineNumber     int32          `json:"line_number"`
	Notes          sql.NullString `json:"notes"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type StockBalance struct {
	ID           uuid.UUID      `json:"id"`
	ProductID    uuid.UUID      `json:"product_id"`
	LocationID   uuid.UUID      `json:"location_id"`
	Quantity     sql.NullString `json:"quantity"`
	ReservedQty  sql.NullString `json:"reserved_qty"`
	AvailableQty sql.NullString `json:"available_qty"`
	LastUpdated  sql.NullTime   `json:"last_updated"`
}

type StockLocation struct {
	ID           uuid.UUID      `json:"id"`
	Code         string         `json:"code"`
	Name         string         `json:"name"`
	LocationType sql.NullString `json:"location_type"`
	IsActive     sql.NullBool   `json:"is_active"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type StockMovement struct {
	ID             uuid.UUID      `json:"id"`
	MovementNumber string         `json:"movement_number"`
	ProductID      uuid.UUID      `json:"product_id"`
	LocationID     uuid.UUID      `json:"location_id"`
	MovementType   string         `json:"movement_type"`
	Quantity       string         `json:"quantity"`
	ReferenceType  sql.NullString `json:"reference_type"`
	ReferenceID    uuid.NullUUID  `json:"reference_id"`
	MovementDate   time.Time      `json:"movement_date"`
	Notes          sql.NullString `json:"notes"`
	CreatedBy      uuid.NullUUID  `json:"created_by"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type Supplier struct {
	ID            uuid.UUID      `json:"id"`
	Code          string         `json:"code"`
	Name          string         `json:"name"`
	ContactPerson sql.NullString `json:"contact_person"`
	Email         sql.NullString `json:"email"`
	Phone         sql.NullString `json:"phone"`
	Address       sql.NullString `json:"address"`
	TaxID         sql.NullString `json:"tax_id"`
	PaymentTerms  sql.NullInt32  `json:"payment_terms"`
	IsActive      sql.NullBool   `json:"is_active"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
}

type SupplierBill struct {
	ID          uuid.UUID      `json:"id"`
	BillNumber  string         `json:"bill_number"`
	SupplierID  uuid.UUID      `json:"supplier_id"`
	PoID        uuid.NullUUID  `json:"po_id"`
	BillDate    time.Time      `json:"bill_date"`
	DueDate     time.Time      `json:"due_date"`
	TotalAmount string         `json:"total_amount"`
	PaidAmount  sql.NullString `json:"paid_amount"`
	Status      sql.NullString `json:"status"`
	Notes       sql.NullString `json:"notes"`
	CreatedBy   uuid.NullUUID  `json:"created_by"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type UnitsOfMeasure struct {
	ID               uuid.UUID      `json:"id"`
	Code             string         `json:"code"`
	Name             string         `json:"name"`
	UnitType         string         `json:"unit_type"`
	IsBaseUnit       sql.NullBool   `json:"is_base_unit"`
	ConversionFactor sql.NullString `json:"conversion_factor"`
	IsActive         sql.NullBool   `json:"is_active"`
	CreatedAt        sql.NullTime   `json:"created_at"`
}

type User struct {
	ID           uuid.UUID    `json:"id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	FullName     string       `json:"full_name"`
	IsActive     sql.NullBool `json:"is_active"`
	LastLoginAt  sql.NullTime `json:"last_login_at"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

type UserRole struct {
	ID         uuid.UUID     `json:"id"`
	UserID     uuid.UUID     `json:"user_id"`
	RoleID     uuid.UUID     `json:"role_id"`
	AssignedAt sql.NullTime  `json:"assigned_at"`
	AssignedBy uuid.NullUUID `json:"assigned_by"`
}
